version: "3"

services:
  web: 
    image: kislak/myapp_web:prod
    ports:
      - "80:3000"
    env_file:
      - .env/prod/web
      - .env/prod/database
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/prod/database
    volumes:
      - db_data:/var/lib/postgresql/data
  db-migrator:
    image: kislak/myapp_web:prod
    command: ["./wait-for", "--timeout=300", "database:5432", "--", "bin/rails", "db:migrate"]
    env_file:
      - .env/prod/web
      - .env/prod/database
    deploy:
      restart_policy:
        condition: none
volumes:
  db_data: